config/routes.rb
Rails.application.routes.draw do
  resources :todo_items
  get 'todo_items/move_up' => 'todo_items#move_up'
  get 'todo_items/move_down' => 'todo_items#move_down'
  resources :todos

  root 'todos#index'

end

app/models/todo.rb
class Todo < ActiveRecord::Base
  has_many :todo_items, -> {order('position ASC')}
end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  belongs_to :todo
  acts_as_list scope: :todo

  def self.create_new_item(list)

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_item, only: [:show, :edit, :update, :destroy]

  # GET /todo_items
  # GET /todo_items.json
  def index
    @list_id = params[:list_id]
    id = @list_id
    if @list_id.nil?
      @list_id = session[:list_id]
      id = @list_id
    end
    puts "The id of the list is #{id}"
    @todo_items = Todo.find(id).todo_items
  end

  # GET /todo_items/1
  # GET /todo_items/1.json
  def show
  end

  # GET /todo_items/new
  def new
    session[:list_id] =  params[:list_id]
    @todo_item = TodoItem.new
  end

  # GET /todo_items/1/edit
  def edit
  end

  # POST /todo_items
  # POST /todo_items.json
  def create
    @todo_item = TodoItem.new(todo_item_params)
    list = Todo.find(session[:list_id])
    @todo_item.todo_id = list.id

    respond_to do |format|
      if @todo_item.save
        format.html { redirect_to todo_items_path }
        format.json { render :show, status: :created, location: @todo_item }
      else
        format.html { render :new }
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def move_up
    todo_item = TodoItem.find(todo_items_params_name)
    todo_item.move_higher
    todo_item.save
    redirect_to 'todo_item#index'
  end

  def move_down
    todo_item = TodoItem.find(todo_items_params_name)
    todo_item.move_lower
    todo_item.save
    redirect_to 'todo_item#index'
  end

  # PATCH/PUT /todo_items/1
  # PATCH/PUT /todo_items/1.json
  def update
    respond_to do |format|
      if @todo_item.update(todo_item_params)
        format.html { redirect_to @todo_item, notice: 'Todo item was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_item }
      else
        format.html { render :edit }
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_items/1
  # DELETE /todo_items/1.json
  def destroy
    @todo_item.destroy
    respond_to do |format|
      format.html { redirect_to todo_items_path, notice: 'Todo item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_item
      if params[:todo_item]
      @todo_item = TodoItem.find(params[:todo_item])
      else
        @todo_item = TodoItem.find(params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_item_params
      params.require(:todo_item).permit(:name, :position)
    end

    def todo_items_params_name
      params.require(:todo_item).permit(:id)
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:title, :notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todolist</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/todo_items/_form.html.erb
<%= form_for(@todo_item) do |f| %>
  <% if @todo_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_item.errors.count, "error") %> prohibited this todo_item from being saved:</h2>

      <ul>
      <% @todo_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.number_field :position %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todo_items/edit.html.erb
<h1>Editing Todo Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo_item %> |
<%= link_to 'Back', todo_items_path %>

app/views/todo_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Todo Items</h1>

<table class="table table-condensed">
  <thead>
    <tr>
      <th>Id</th>
      <th>Item Name</th>
      <th>Position</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todo_items.each do |todo_item| %>
      <tr>
        <td><%= todo_item.id %></td>
        <td><%= todo_item.name %></td>
        <td><%= todo_item.position %></td>
        <td><%=link_to 'Move up', todo_items_move_up_path(todo_item: todo_item), class: 'btn btn-success'%></td>
        <td><%=link_to 'Move down', todo_items_move_down_path(todo_item: todo_item), class: 'btn btn-primary'%></td>

        <td><%= link_to 'Destroy', todo_item, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo item', new_todo_item_path(list_id: @list_id) %>

app/views/todo_items/new.html.erb
<h1>New Todo Item</h1>

<%= render 'form' %>

<%= link_to 'Back', todo_items_path %>

app/views/todo_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item Name:</strong>
  <%= @todo_item.name %>
</p>

<p>
  <strong>Position:</strong>
  <%= @todo_item.position %>
</p>

<%= link_to 'Edit', edit_todo_item_path(@todo_item) %> |
<%= link_to 'Back', todo_items_path(list_id: @todo_item.todo_id) %>

app/views/todos/_form.html.erb
<%= form_for(@todo) do |f| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% @todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Editing Todo</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Todos</h1>

<table class="table table-condensed">
  <thead>
    <tr>
      <th>Id</th>
      <th>Title</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td><%= todo.id %></td>
        <td><%= todo.title %></td>
        <td><%= todo.notes %></td>
        <td><%= link_to 'Add Items', todo_items_path(list_id: todo.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo', new_todo_path, class:'btn btn-info btn-lg' %>

app/views/todos/new.html.erb
<h1>New Todo</h1>

<%= render 'form' %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @todo.title %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @todo.notes %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>